from django.urls import path, include
from . import views
from django.contrib import admin

urlpatterns = [
    path('modelList', views.modelList),
    path('query', views.query),
    path('genView', views.genView),
    path('modelview', views.modelView),
    path('bestPercentages', views.bestPercentages),
    path('filterZipCodes', views.filterZipCodes),
    path('getPercentageVariation', views.getPercentageVartation),
    path('getModelInfos', views.getModelInfos),
    path('connexion', views.connexion),
    path('deconnexion', views.deconnexion),
    path('inscription', views.inscription),
    path('admin/', admin.site.urls),
    path('manageDatabase', views.manageDatabase),
    path('sendFileDatas', views.sendFileDatas),
    path('getMainPercentages', views.getMainPercentages),
    path('isPremium', views.askIfPremium),
    path('getImage', views.getImage),
    path('getEncryptedPdf', views.getEncryptedPdf),
    path('getEncryptedProtected', views.getEncryptedProtected),
    path('getMainPageImages', views.getMainPageImages),
    path('registerCommand', views.registerCommand),
    path('getUser', views.getUser),
    path('isUserLoggedIn', views.isUserLoggedIn),
    path('addCompareView', views.addCompareView),
    path('getCompareView', views.getCompareView),
    path('addItemIntoView', views.addItemIntoView),
    path('addToFavorites', views.addToFavorites),
    path('renameView', views.renameView),
    path('deleteView', views.deleteView),
    path('getModelDatasComparator', views.getModelDatasComparator),
    path('getModelUrl', views.getModelUrl),
    path('modifyItemPos', views.modifyItemPos),
    path('getMapDatas', views.getMapDatas),
    path('deleteItem', views.deleteItem),
    ]