# Generated by Django 3.0.5 on 2020-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyings',
            name='command_number',
        ),
        migrations.RemoveField(
            model_name='buyings',
            name='numero',
        ),
        migrations.AddField(
            model_name='buyings',
            name='order_paypal_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyings',
            name='payer_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
