# Generated by Django 3.0.5 on 2020-05-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200528_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyings',
            name='item',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
